title: Poker on the console
description: >-
  Create a simple Poker game using https://www.pokerapi.dev/ while reviewing
  basic JS fundamentals and learning ES6+ and more advanced JS concepts.
template:
  repo: poker-on-the-console-template
  name: poker-on-the-console
  description: Repo of simple Poker game using pokerapi.dev
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issue_comment.created
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
      - type: gate
    video: 'https://www.youtube.com/embed/1gX81kmCpVg'
